on: [push]

jobs:
  test:
    name: Check code integrity
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node js (v16)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install npm deps
        run: npm ci
      
      - name: Check code format
        run: npm run format

      - name: Liniting
        run: npm run lint
      
      - name: Run test suite
        run: npm test

  build:
    name: Run build process
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node js (v16)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install npm deps
        run: npm ci
      
      - name: Check code format
        run: npm run build

      - name: Store the build manifest
        uses: actions/upload-artifact@v3
        with:
          name: manifest.json
          path: ./build/manifest.json
          if-no-files-found: error
          retention-days: 3
    